apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: udagram-729925515107-dev
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: testing
  POSTGRES_DB: postgres
  POSTGRES_HOST: udagram-db.cgfnjeaoxocd.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100
metadata:
  name: env-config
