# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
docker build -t reverseproxy ./reverseproxy
# Do similar for other three images

# Tagging
docker tag reverseproxy tantt5/reverseproxy:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push tantt5/reverseproxy:v1
# Do similar for other three images