language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

script:
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy matheusciaramella/udagram-reverseproxy:latest
  - docker tag udagram-api-user matheusciaramella/udagram-api-user:latest
  - docker tag udagram-api-feed matheusciaramella/udagram-api-feed:latest
  - docker tag udagram-frontend matheusciaramella/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push matheusciaramella/udagram-api-user:latest
  - docker push matheusciaramella/udagram-api-feed:latest
  - docker push matheusciaramella/udagram-frontend:latest
  - docker push matheusciaramella/reverseproxy:latest
