language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests. Yes There will be tests"

script:
  - docker --version # prints version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  # Tagging
  - docker tag udagram-reverseproxy thimee/udagram-reverseproxy
  - docker tag udagram-api-feed thimee/udagram-api-feed
  - docker tag udagram-api-user thimee/udagram-api-user
  - docker tag udagram-api-frontend thimee/udagram-api-frontend:local

# Tasks to perform after process is successful
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thimee/udagram-reverseproxy
  - docker push thimee/udagram-api-feed
  - docker push thimee/udagram-api-user
  - docker push thimee/udagram-frontend:local