## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy
## Tagging
  - docker tag udagram-api-feed dattm283/udagram-api-feed:v1
  - docker tag udagram-api-user dattm283/udagram-api-user:v1
  - docker tag udagram-api-frontend dattm283/udagram-api-frontend:v1
  - docker tag udagram-api-reverseproxy dattm283/udagram-api-reverseproxy:v1
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dattm283/udagram-api-feed:v1
  - docker push dattm283/udagram-api-user:v1
  - docker push dattm283/udagram-api-frontend:v1
  - docker push dattm283/udagram-api-reverseproxy:v1