language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
<<<<<<< HEAD
  - docker build -t udagram-frontend ./udagram-frontend:v3
  - docker tag udagram-frontend ocheruiyot/udagram-frontend:latest
  - docker push ocheruiyot/udagram-frontend:v3

  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./reverseproxy:v4
  - docker tag udagram-reverseproxy ocheruiyot/reverseproxy:latest
  - docker push ocheruiyot/reverseproxy:v4

  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user:v2
  - docker tag udagram-api-user ocheruiyot/udagram-api-user:latest
  - docker push ocheruiyot/udagram-api-user:v2

  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed:v1
  - docker tag udagram-api-feed ocheruiyot/udagram-api-feed:latest
  - docker push ocheruiyot/udagram-api-feed:v1

=======
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend ocheruiyot/udagram-frontend:latest
>>>>>>> d9d812e148a1ab4812ea4525e82e997ad7ea5954

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ocheruiyot/udagram-frontend
<<<<<<< HEAD

  
=======
>>>>>>> d9d812e148a1ab4812ea4525e82e997ad7ea5954
