services:
  - docker

script:

  #Build
  - echo '_______begining build'
  - docker build -t udagram-api-feed:v3 ./udagram-api-feed
  - docker build -t udagram-api-user:v3 ./udagram-api-user
  - docker build -t udagram-frontend:v3 ./udagram-frontend
  - docker build -t reverseproxy:v3 ./udagram-reverseproxy

  #Tagging
  - echo '______beigning tag'
  - docker tag udagram-api-feed:v3 ngtrantan99/udagram-api-feed:v3
  - docker tag udagram-api-user:v3 ngtrantan99/udagram-api-user:v3
  - docker tag udagram-frontend:v3 ngtrantan99/udagram-frontend:v3
  - docker tag reverseproxy:v3 ngtrantan99/reverseproxy:v3

  - echo 'Docker Image ls___'
  - docker image ls

after success:
    - echo '__Login__'
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - echo '_____push to Docker Hub'
    #ECHO 'username', 'password', $DOCKER_USERNAME $DOCKER_PASSWORD
    # Pushing
    - echo '_____begining push image'
    - docker push ngtrantan99/udagram-api-feed:v3
    - docker push ngtrantan99/udagram-api-user:v3
    - docker push ngtrantan99/udagram-frontend:v3
    - docker push ngtrantan99/reverseproxy:v3


    #update test 1