language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logginadd
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed timidev1/udagram-api-feed:v1
  - docker tag udagram-api-user timidev1/udagram-api-user:v1
  - docker tag reverseproxy timidev1/reverseproxy:v1
  - docker tag udagram-frontend timidev1/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push timidev1/udagram-api-feed:v1
  - docker push timidev1/udagram-frontend:v1
  - docker push timidev1/reverseproxy:v1
  - docker push timidev1/udagram-api-user:v1