language: node_js
node_js: 
   - 14

services:
  - docker
# pre-testing installs
install:
  - echo "nothing needs to be installed"

# scripts to be run such as tests
before_scripts:
  - echo "no tests. yes there will be tests"

# Build image
- docker --version # print the version for logging here.
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker build -t udagram-frontend ./udagram-frontend
# Tagging
- docker tag udagram-api-feed mohamedahmedfaramawy/udagram-api-feed:v1
- docker tag udagram-api-user mohamedahmedfaramawy/udagram-api-user:v1
- docker tag udagram-reversproxy mohamedahmedfaramawy/udagram-reversproxy:v1
- docker tag udagram-frontend mohamedahmedfaramawy/udagram-frontend:v1
# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push mohamedahmedfaramawy/udagram-api-feed:v1
- docker push mohamedahmedfaramawy/udagram-api-user:v1
- docker push mohamedahmedfaramawy/udagram-reversproxy:v1
- docker push mohamedahmedfaramawy/udagram-frontend:v1


