language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests. yes there will be tests"

script:
  - docker --version #print version docker
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  #Tagging
  - docker tag udagram-reverseproxy duong123/udagram-reverseproxy:v4a
  - docker tag udagram-api-feed duong123/udagram-api-feed:v4a
  - docker tag udagram-api-user duong123/udagram-api-user:v4a
  - docker tag udagram-frontend duong123/udagram-frontend:local
#Tasks to perform after the process is successful
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push duong123/udagram-reverseproxy:v4a
  - docker push duong123/udagram-api-feed:v4a
  - docker push duong123/udagram-api-user:v4a
  - docker push duong123/udagram-frontend:local