version: "3"
services:
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed