version: "3"
services:
  reverseproxy:
      image: reverseproxy:v3a
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - api-user
        - api-feed
  api-user:
    image: udagram-api-user:v3a
    environment:
      POSTGRES_USERNAME: mizile
      POSTGRES_PASSWORD: mizile123
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres.cu50d2w51m7p.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udacitybucket99
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  api-feed:
    image: udagram-api-feed:v3a
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: mizile
      POSTGRES_PASSWORD: mizile123
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres.cu50d2w51m7p.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udacitybucket99
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
