version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local