version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
    env_file:
      - ./.env
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
    env_file:
      - ./.env
    volumes:
      - $HOME/.aws:/root/.aws
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
    ports:
      - "8100:80"
