version: "3"
services:
  reverseproxy:
    build:
      context: ./reverse-proxy
    image: udagram-reverse-proxy
  backend_user:
    build:
      context: ./api-user
    image: udagram-api-user
  backend_feed:
    build:
      context: ./api-feed
    image: udagram-api-feed
  frontend:
    build:
      context: ./ui
    image: udagram-frontend:local