version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abc123456
      POSTGRES_DB: postgres 
      POSTGRES_HOST: database-1.csvfrqthpb12.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: test-120094232232-dev
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abc123456
      POSTGRES_DB: postgres 
      POSTGRES_HOST: database-1.csvfrqthpb12.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: test-120094232232-dev
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"