apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  POSTGRES_HOST: postgres.cod2be2u6ezj.us-east-2.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: udagram-819379974179-dev
  AWS_REGION: us-east-2
  AWS_PROFILE: default
  JWT_SECRET: hello
  URL: http://localhost:8100