apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: transytai12a1/reverseproxy:v6
        name: reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
