apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: zeyadmobarez/reverseproxy:v4a
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "400m"
        ports:
        - containerPort: 8080
      restartPolicy: Always