version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.22.12
    # machine: 
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: 
             name: Build docker images
             command: |
                      node --version
                      echo "------- Building images ---------"
                      docker build -t udagram-api-feed ./udagram-api-feed
                      docker build -t udagram-api-user ./udagram-api-user
                      docker build -t udagram-frontend ./udagram-frontend
                      docker build -t udagram-reverseproxy ./udagram-reverseproxy

                      echo "------- Start tagging images ---------"
                      docker tag udagram-api-feed peggylicious/udagram-api-feed:v4
                      docker tag udagram-api-user peggylicious/udagram-api-user:v4
                      docker tag udagram-frontend peggylicious/udagram-frontend:v4
                      docker tag udagram-reverseproxy peggylicious/udagram-reverseproxy:v4

                      echo "------- Log in to docker hub ---------"

                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                      docker push peggylicious/udagram-api-feed:v4
                      docker push peggylicious/udagram-api-user:v4
                      docker push peggylicious/udagram-frontend:v4
                      docker push peggylicious/udagram-reverseproxy:v4
# Do similar for other three images
# Added env variables
