apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-frontend
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: udagram-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
