apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - name: 8100-80
    port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-frontend
  type: ClusterIP
status:
  loadBalancer: {}