version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: emmanuelstanley/udagram-frontend
    docker:
      - image: cimg/base:2021.04
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Testing Environment
          command: echo "Testing Environments"
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t udagram-frontend .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar udagram-frontend
      - persist_to_workspace:
          root: .
          paths:
          - ./image.tar
  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker Image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to DockerHub
          command: | 
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag udagram-frontend emmanuelstanley/udagram-frontend:v1
            docker push emmanuelstanley/udagram-frontend:v1
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-tag:
          requires:
            - build
          filters:
            branches:
              only: master