apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: tinhpt4-842694625473-bucket
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: testing
  POSTGRESS_DB: postgres
  POSTGRESS_HOST: udacity-project-3.c51qeabvrgda.us-east-1.rds.amazonaws.com
  URL: http://a9b4f139f8a4943cd95d45cf1ec3696e-1192894825.us-east-1.elb.amazonaws.com
metadata:
  name: env-config