apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-map
data:
  AWS_BUCKET: arn:aws:s3:::bucket-681231710297-dev
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  JWT_SECRET: testing
  POSTGRES_DB: postgres
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: lamdt12345678
  POSTGRES_HOST: database-681231710297.cbzjyzo6g8ww.us-east-1.rds.amazonaws.com
  URL: http://localhost:8100


