apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: tifarafa/reverseproxy:0.1.15
        name: reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always  
       