name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push feed api
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-feed
          push: true
          tags: michealgabriel/udagram-api-feed:v1
      -
        name: Build and push user api
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-api-user
          push: true
          tags: michealgabriel/udagram-api-user:v1
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-frontend
          push: true
          tags: michealgabriel/udagram-frontend:v1
      -
        name: Build and push reverse proxy
        uses: docker/build-push-action@v3
        with:
          context: ./udagram-reverseproxy
          push: true
          tags: michealgabriel/udagram-reverseproxy:v1